"""
BioAlert — Human/Animal Intrusion Detection System
====================================================
File   : train.py
Purpose: Train (or resume training of) the YOLOv8n-cls classification
         model that powers BioAlert's edge inference pipeline.

Behaviour
---------
The script automatically decides what to do at runtime:

  • If a checkpoint (last.pt) already exists in the expected Drive
    location → training is **resumed** from where it left off.

  • If no checkpoint is found → a **fresh training run** is started
    from the official pretrained YOLOv8n-cls backbone.

This removes the need to maintain separate "start" and "resume"
notebooks — a single file handles both cases safely.

Prerequisites
-------------
Run setup.py first to mount Drive and extract the dataset.

Model output
------------
Weights are saved to:
  /content/drive/MyDrive/intrusion_dataset/train_v2/weights/
    best.pt   — highest-accuracy checkpoint (use this for deployment)
    last.pt   — most recent epoch checkpoint (used for resuming)

Author : Hassan Adewale Abdulmalik
Project: BioAlert (Final Year Project)
"""

import os
from ultralytics import YOLO


# ---------------------------------------------------------------------------
# Configuration
# Adjust these constants if your Drive layout or hardware changes.
# ---------------------------------------------------------------------------

# Dataset root — produced by setup.py
DATA_DIR = '/content/dataset/human_animal_dataset_v2'

# Where training outputs are saved (must be on Drive to persist across sessions)
PROJECT_DIR = '/content/drive/MyDrive/intrusion_dataset'
RUN_NAME    = 'train_v2'

# Checkpoint path (auto-generated by a previous training run)
CHECKPOINT = os.path.join(PROJECT_DIR, RUN_NAME, 'weights', 'last.pt')

# Pretrained backbone used when starting from scratch
BASE_MODEL = 'yolov8n-cls.pt'

# Training hyperparameters
EPOCHS   = 50    # total epochs (both fresh and resume honour this)
IMG_SIZE = 224   # input resolution (px) — kept small for ESP32-CAM compatibility
BATCH    = 32    # batch size — tuned for Colab T4 GPU
DEVICE   = 'cuda'
PATIENCE = 10    # early-stopping patience (fresh runs only)


# ---------------------------------------------------------------------------
# Auto-detect: resume vs fresh start
# ---------------------------------------------------------------------------

if os.path.exists(CHECKPOINT):
    # -----------------------------------------------------------------------
    # RESUME — a previous run was interrupted or the session expired.
    # Ultralytics picks up from the exact epoch stored in last.pt.
    # -----------------------------------------------------------------------
    print("=" * 60)
    print("Checkpoint detected — resuming training")
    print(f"  {CHECKPOINT}")
    print("=" * 60, "\n")

    model = YOLO(CHECKPOINT)

    model.train(
        data    = DATA_DIR,
        epochs  = EPOCHS,
        imgsz   = IMG_SIZE,
        batch   = BATCH,
        device  = DEVICE,
        project = PROJECT_DIR,
        name    = RUN_NAME,
        resume  = True,           # critical — tells YOLO to continue from last epoch
    )

else:
    # -----------------------------------------------------------------------
    # FRESH START — no checkpoint exists yet.
    # Begins from the official pretrained YOLOv8n-cls backbone.
    # -----------------------------------------------------------------------
    print("=" * 60)
    print("No checkpoint found — starting fresh training run")
    print(f"  Backbone: {BASE_MODEL}")
    print("=" * 60, "\n")

    model = YOLO(BASE_MODEL)

    model.train(
        data    = DATA_DIR,
        epochs  = EPOCHS,
        imgsz   = IMG_SIZE,
        batch   = BATCH,
        device  = DEVICE,
        project = PROJECT_DIR,
        name    = RUN_NAME,
        patience = PATIENCE,      # stop early if val loss plateaus
    )


# ---------------------------------------------------------------------------
# Post-training summary
# ---------------------------------------------------------------------------
best_weights = os.path.join(PROJECT_DIR, RUN_NAME, 'weights', 'best.pt')

print("\n" + "=" * 60)
print("Training complete.")
print(f"  Weights directory : {PROJECT_DIR}/{RUN_NAME}/weights/")
print(f"  Best weights      : {'found ✓' if os.path.exists(best_weights) else 'NOT FOUND ✗'}")
print("=" * 60)
print("\nNext step: copy best.pt to your Flask server or ESP32 OTA endpoint.")
